---
name: API Testing - Newman
on:
    workflow_dispatch:

jobs:
    newman:
        name: Run collections + tests with Newman
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - uses: SimonScholz/postman-newman-action@main
              with:
                  collection: test/collection.json
